server.port: 8888
spring:
  profiles:
    active: git
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config
        git:
          uri: https://github.com/Youki-code/loopnurture-java
          default-label: develop
          searchPaths: config

management:
  tracing:
    zipkin:
      enabled: false

