spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  cloud:
    gateway:
      default-filters:
        - name: CircuitBreaker
          args:
            name: defaultCircuitBreaker
            fallbackUri: forward:/fallback
        - name: Retry
          args:
            retries: 1
            statuses: SERVICE_UNAVAILABLE
            methods: POST
      routes:
        - id: users-service
          uri: lb://users-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2
        - id: mail-service
          uri: lb://mail-service
          predicates:
            - Path=/api/mail/**
          filters:
            - StripPrefix=2

management:
  tracing:
    zipkin:
      enabled: false

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888

management:
  tracing:
    zipkin:
      enabled: false
