spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  cloud:
    gateway:
      default-filters:
        - name: CircuitBreaker
          args:
            name: defaultCircuitBreaker
            fallbackUri: forward:/fallback
        - name: Retry
          args:
            retries: 1
            statuses: SERVICE_UNAVAILABLE
            methods: POST
      routes:
        # Users service - cover v1 endpoints
        - id: users-service
          uri: lb://users-service
          predicates:
            - Path=/api/v1/users/**,/api/v1/auth/**,/api/v1/organizations/**
          filters:
            - StripPrefix=2

        # Mail service AI endpoints
        - id: mail-ai
          uri: lb://mail-service
          predicates:
            - Path=/api/v1/ai/**
          filters:
            - StripPrefix=2

        # Mail service marketing/template, email/rules etc.
        - id: mail-marketing
          uri: lb://mail-service
          predicates:
            - Path=/api/v1/marketing/**,/api/v1/email/**
          filters:
            - StripPrefix=2

      global-cors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: false

management:
  tracing:
    zipkin:
      enabled: false

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888

management:
  tracing:
    zipkin:
      enabled: false
