spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:petclinic}?serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASS:petclinic}
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: ${SERVER_PORT:8082}

logging:
  level:
    root: WARN
    org.springframework: WARN 