spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      schema-locations: classpath*:db/hsqldb/schema.sql
      data-locations: classpath*:db/hsqldb/data.sql
      mode: always

# Default profile - HSQLDB
  datasource:
    url: jdbc:hsqldb:mem:visits
    username: sa
    password:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver

---
spring:
  config:
    activate:
      on-profile: mysql
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      schema-locations: classpath*:db/mysql/schema.sql
      data-locations: classpath*:db/mysql/data.sql
      mode: always
      platform: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/petclinic?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: petclinic
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8082

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE 