spring:
  jpa:
    hibernate:
      ddl-auto: update  # 可以根据需要改为 none 或 validate
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      schema-locations: classpath*:db/postgresql/schema.sql
      data-locations: classpath*:db/postgresql/data.sql
  datasource:
    # Supabase连接配置
    url: jdbc:postgresql://${SUPABASE_HOST:db.example.supabase.co}:${SUPABASE_PORT:5432}/${SUPABASE_DATABASE:postgres}
    username: ${SUPABASE_USER:postgres}
    password: ${SUPABASE_PASSWORD:your-password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:5}
      minimum-idle: ${DB_MIN_IDLE:2}
      idle-timeout: 300000
      connection-timeout: 20000
      connection-test-query: SELECT 1
      # SSL配置
      properties:
        ssl: true
        sslmode: require

server:
  port: ${SERVER_PORT:8082}

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE 