spring:
  application:
    name: users-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://aws-0-us-west-1.pooler.supabase.com:6543/postgres?user=postgres.cilxaqxdcffzpggwjphz&password=loopnurture1a2b3c4d!
    username: postgres.cilxaqxdcffzpggwjphz
    password: loopnurture1a2b3c4d!
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 300000
      connection-timeout: 20000
      connection-test-query: SELECT 1
      leak-detection-threshold: 60000
      pool-name: UsersServiceHikariCP
      data-source-properties:
        prepareThreshold: 0
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
        temp:
          use_jdbc_metadata_defaults: false
  flyway:
    enabled: false

server:
  port: 8081

jwt:
  secret: loopnurture_jwt_secret_key_please_change_in_production
  expiration: 86400

# Disable Zipkin reporter
management:
  tracing:
    zipkin:
      enabled: false 