spring:
  application:
    name: users-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://aws-0-us-west-1.pooler.supabase.com:6543/postgres
    username: postgres.cilxaqxdcffzpggwjphz
    password: loopnurture1a2b3c4d!
    hikari:
      pool-name: UsersServiceHikariCP
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      data-source-properties:
        prepareThreshold: 0  # 禁用 PostgreSQL 服务器端 prepared statement，避免 "already exists" 错误
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # 禁用类型检查，允许SMALLINT和INTEGER之间的转换
        jdbc:
          time_zone: UTC
        # 配置类型映射
        types:
          preferred-instant-jdbc-type: TIMESTAMP
  flyway:
    enabled: false
    # 已停用 Flyway，采用 schema SQL 初始化

server:
  port: 8081

jwt:
  secret: loopnurture_jwt_secret_key_please_change_in_production
  expiration: 86400 # 24 hours in seconds

# Disable Zipkin reporter locally
management:
  tracing:
    zipkin:
      enabled: false
    exporter: none  # Disable Zipkin/OTLP export
    sampling:
      probability: 0

google:
  oauth:
    client-id: "${GOOGLE_CLIENT_ID:dummy-client-id}"
    verify-token: false
