spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: mail-service
  datasource:
    url: jdbc:postgresql://aws-0-us-west-1.pooler.supabase.com:6543/postgres
    username: postgres.cilxaqxdcffzpggwjphz
    password: loopnurture1a2b3c4d!
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      leak-detection-threshold: 60000
      validation-timeout: 5000
      auto-commit: true
      data-source-properties:
        prepareThreshold: 0  # 禁用服务器端 prepared statement，避免重复声明
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
          batch_size: 20
          batch_versioned_data: true
        temp:
          use_jdbc_metadata_defaults: false
        connection:
          provider_disables_autocommit: false
        transaction:
          auto_commit: true
          jta:
            platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
  flyway:
    enabled: false

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# SendGrid Configuration
sendgrid:
  api-key: "${SENDGRID_API_KEY:your-sendgrid-api-key-here}"

server:
  port: 8082

# 用户服务直连地址，避免走注册中心解析到错误实例
services:
  user:
    url: http://localhost:8081

# Disable Zipkin reporter locally
management:
  tracing:
    zipkin:
      enabled: false 