spring:
  application:
    name: mail-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db.qvyxvqbxvhxvwxvjxvwx.supabase.co:5432/postgres
    username: tangyuqi764@163.com
    password: 1c2i3a2222
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      connection-test-query: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
        temp:
          use_jdbc_metadata_defaults: false

# SendGrid Configuration
sendgrid:
  api-key: ${SENDGRID_API_KEY}

server:
  port: 8082

services:
  user:
    url: http://localhost:8081 