spring:
  application:
    name: admin-server
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}

management:
  tracing:
    zipkin:
      enabled: false

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888

management:
  tracing:
    zipkin:
      enabled: false
